export default [
  {
    image: "./imgs/sale-imgs/doom-eternal.jpg",
    name: "Doom Eternal",
    price: 1499,
    discount: 20,
    category: "top",
  },
  {
    image: "./imgs/sale-imgs/assasins-creed-syndicate.jpg",
    name: "Assassins's creed syndicate",
    price: 939,
    discount: 25,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/dota-2.jpg",
    name: "dota 2",
    price: 1739,
    discount: 33,
    category: "top",
  },
  {
    image: "./imgs/sale-imgs/far-cry-6.jpg",
    name: "far cry 6",
    price: 2499,
    discount: 40,
    category: "top",
  },
  {
    image: "./imgs/sale-imgs/genshin-impact.jpg",
    name: "genshin impact",
    price: null,
    discount: null,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/gta-online.jpg",
    name: "gta online",
    price: 2399,
    discount: 50,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/last-of-us.jpg",
    name: "the last of us part 1",
    price: 3000,
    discount: 45,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/mortal-kombat-X.jpg",
    name: "mortal kombat x",
    price: 2999,
    discount: 35,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/league-of-legends.jpg",
    name: "league of legends",
    price: 1600,
    discount: 25,
    category: "top",
  },
  {
    image: "./imgs/sale-imgs/mafia-2.jpg",
    name: "mafia 2",
    price: 399,
    discount: null,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/minecraft.jpg",
    name: "minecraft",
    price: 999,
    discount: 15,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/saint-reboot.jpg",
    name: "Saints Row",
    price: 1859,
    discount: 55,
    category: "top",
  },
  {
    image: "./imgs/sale-imgs/rdr-2.jpg",
    name: "the read dead redemption 2",
    price: 3199,
    discount: 35,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/valorant.jpg",
    name: "valorant",
    price: null,
    discount: null,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/fortnite-resize.jpg",
    name: "fornite",
    price: null,
    discount: null,
    category: "most",
  },
  {
    image: "./imgs/sale-imgs/nfs-heat.jpg",
    name: "nfs heat",
    price: 2999,
    discount: 30,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/watch-dogs-legion.jpg",
    name: "watch dogs: legion deluxe edition",
    price: 3499,
    discount: 40,
    category: "wishlist",
  },
  {
    image: "./imgs/sale-imgs/gta-online.jpg",
    name: "gta online",
    price: 2399,
    discount: 50,
    category: "top",
  },
];
