export default [
  {
    image: "./imgs/sale-imgs/assasins-creed-syndicate.jpg",
    name: "assassin's creed syndicate",
    discount: 25,
    price: 939,
  },
  {
    image: "./imgs/sale-imgs/doom-eternal.jpg",
    name: "doom eternal",
    discount: 17,
    price: 1499,
  },
  {
    image: "./imgs/sale-imgs/dota-2.jpg",
    name: "dota 2",
    discount: 33,
    price: 1739,
  },
  {
    image: "./imgs/sale-imgs/far-cry-6.jpg",
    name: "far cry 6",
    discount: 40,
    price: 2499,
  },
  {
    image: "./imgs/sale-imgs/genshin-impact.jpg",
    name: "genshin impact",
    discount: null,
    price: null,
  },
  {
    image: "./imgs/sale-imgs/gta-online.jpg",
    name: "gta online",
    discount: 50,
    price: 2399,
  },
  {
    image: "./imgs/sale-imgs/last-of-us.jpg",
    name: "the last of us part 1",
    discount: 45,
    price: 3999,
  },
  {
    image: "./imgs/sale-imgs/league-of-legends.jpg",
    name: "league of legends",
    discount: 25,
    price: 1600,
  },
  {
    image: "./imgs/sale-imgs/mafia-2.jpg",
    name: "Mafia 2",
    discount: null,
    price: 399,
  },
  {
    image: "./imgs/sale-imgs/minecraft.jpg",
    name: "Minecraft",
    discount: 15,
    price: 999,
  },
  {
    image: "./imgs/sale-imgs/mortal-kombat-X.jpg",
    name: "mortal kombat x",
    discount: 35,
    price: 2999,
  },
  {
    image: "./imgs/sale-imgs/nfs-heat.jpg",
    name: "nfs heat",
    discount: 30,
    price: 2999,
  },
  {
    image: "./imgs/sale-imgs/pubg.jpg",
    name: "player unknown battlegrounds",
    discount: null,
    price: null,
  },
  {
    image: "./imgs/sale-imgs/rdr-2.jpg",
    name: "the read dead redemption 2",
    discount: 35,
    price: 3199,
  },
  {
    image: "./imgs/sale-imgs/saints-row-4.jpg",
    name: "the saints row 4 re-elected",
    discount: 75,
    price: 1000,
  },
  {
    image: "./imgs/sale-imgs/sleeping-dogs.jpg",
    name: "sleeping dogs",
    discount: 50,
    price: 300,
  },
  {
    image: "./imgs/sale-imgs/valorant.jpg",
    name: "valorant",
    discount: null,
    price: null,
  },
  {
    image: "./imgs/sale-imgs/watch-dogs-legion.jpg",
    name: "watch dogs: legion deluxe edition",
    discount: 40,
    price: 3499,
  },
  {
    image: "./imgs/sale-imgs/wolfenstein.jpg",
    name: "wolfenstein: the new order",
    discount: 55,
    price: 1179,
  },
];
