export default [
  {
    image: "./imgs/games-grid-2/touch-type-tale.jpg",
    name: "Touch Type Tale",
    price: 1495.6,
    discount: 10,
    category: "new",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/world-war-1.jpg",
    name: "Trenches - World War 1 Horror",
    price: 359,
    discount: null,
    category: "new",
    available: null,
    alert: true,
  },
  {
    image: "./imgs/games-grid-2/barrett-foster.jpg",
    name: "Barrett Foster Prologue",
    price: null,
    discount: null,
    category: "new",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/9-years-of-shadows.jpg",
    name: "9 Years of Shadows",
    price: 469,
    discount: 20,
    category: "new",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/water-2050.jpg",
    name: "Water 2050",
    price: 139,
    discount: null,
    category: "new",
    available: null,
    alert: true,
  },

  {
    image: "./imgs/games-grid-2/jackbox-1.jpg",
    name: "The Jackbox Party Pack",
    price: 595,
    discount: null,
    category: "top",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/jackbox-3.jpg",
    name: "Jackbox Party Pack 3",
    price: 595,
    discount: null,
    category: "top",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/flatout-2.jpg",
    name: "Flatout 2",
    price: 239,
    discount: null,
    category: "top",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/celeste.jpg",
    name: "Celeste",
    price: 595,
    discount: null,
    category: "top",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/hades.jpg",
    name: "Hades",
    price: 595,
    discount: null,
    category: "top",
    available: null,
    alert: false,
  },
  {
    image: "./imgs/sale-imgs/last-of-us.jpg",
    name: "The Last of Us™ Part I",
    price: 3999,
    discount: null,
    category: "soon",
    available: "Available 03/28/23",
    alert: false,
  },
  {
    image: "./imgs/games-grid-2/crime-boss.jpg",
    name: "Crime Boss: Rockay City",
    price: 2599,
    discount: 20,
    category: "soon",
    available: "Available 03/28/23",
    alert: true,
  },
  {
    image: "./imgs/games-grid-2/home-wars.jpg",
    name: "Home Wars",
    price: null,
    discount: null,
    category: "soon",
    available: "Available 03/29/23",
    alert: true,
  },
  {
    image: "./imgs/games-grid-2/gripper.jpg",
    name: "Gripper",
    price: null,
    discount: null,
    category: "soon",
    available: "Available 03/29/23",
    alert: true,
  },
  {
    image: "./imgs/games-grid-2/stellar-interface.jpg",
    name: "Stellar Interface",
    price: null,
    discount: null,
    category: "soon",
    available: "Available 03/30/23",
    alert: true,
  },
];
